CREATE TABLE orders (status VARCHAR(20) NOT NULL, payment_reference VARCHAR(64) DEFAULT NULL, id VARCHAR(36) NOT NULL, email VARCHAR(255) NOT NULL, country VARCHAR(2) NOT NULL, vat_rate SMALLINT NOT NULL, PRIMARY KEY (id));

CREATE TABLE order_lines (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, ebook_id VARCHAR(36) NOT NULL, unit_price VARCHAR(32) NOT NULL, quantity INTEGER NOT NULL, order_id VARCHAR(36) NOT NULL, CONSTRAINT FK_CC9FF86B8D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) NOT DEFERRABLE INITIALLY IMMEDIATE);

CREATE INDEX IDX_CC9FF86B8D9F6D38 ON order_lines (order_id);
