CREATE TABLE orders (status VARCHAR(20) NOT NULL, payment_reference VARCHAR(64) DEFAULT NULL, id VARCHAR(36) NOT NULL, email VARCHAR(255) NOT NULL, country VARCHAR(2) NOT NULL, vat_rate SMALLINT NOT NULL, PRIMARY KEY (id));

CREATE TABLE order_lines (id INT AUTO_INCREMENT NOT NULL, ebook_id VARCHAR(36) NOT NULL, unit_price VARCHAR(32) NOT NULL, quantity INT NOT NULL, order_id VARCHAR(36) NOT NULL, INDEX IDX_CC9FF86B8D9F6D38 (order_id), PRIMARY KEY (id));

ALTER TABLE order_lines ADD CONSTRAINT FK_CC9FF86B8D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id);
